version: '3.8'

services:
  frontend:
    build:
      context: ./motivaa-frontend/
      dockerfile: ./local-run/Dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
    - BACKEND_URL=http://backend:8093/v3/api-docs
    

  backend:
    build:
      context: ./motivaa-backend/
      dockerfile: ./local-run/Dockerfile
    ports:
      - "8093:8093"
    depends_on:
      - elasticsearch
      - motivaa-keycloak
    environment:
        - ELASTICSEARCH=http://elasticsearch:9200

#  mysql:
#    image: mysql:latest
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: Motivaa
#    ports:
#      - "3306:3306"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false ## disable SSL, auto https -enforce
    ports:
      - "9200:9200"
  motivaa-keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: motivaa-keycloak
    volumes:
      - keycloak_data:/opt/keycloak/themes
      - ./keycloak-themes/themes:/opt/keycloak/themes
      - ./keycloak-themes/providers:/opt/keycloak/providers
      - ./import:/opt/keycloak/data/import
    command: ["start-dev", "--import-realm", "--verbose"]
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: hadmin
      REALM_NAME: Motivaa


volumes:
  keycloak_data: