# This workflow will build a Java project with Maven and run the unit tests, then deploy the backend to Docker repo

name: Run unit tests and deploy to Docker repo

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: run backend unit tests with maven
      run: |
        cd motivaa-backend/
        mvn test -P test
  deploy_to_docker_repo:
    needs: run_unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: rplesz/motivaa-backend
          tags: v1, latest
          registry: docker.io
          dockerfile: ./motivaa-backend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
