# This workflow will build a Java project with Maven and run the unit tests

name: Run unit tests after every commit

on:
  push:
    branches-ignore: [ "main" ]
  pull_request:
    branches-ignore: [ "main" ]

jobs:
  run_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: run backend unit tests with maven
      run: |
        cd habito-backend/
        mvn test