name: Run frontend tests after every commit

on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches-ignore: ["main"]

jobs:
  run_frontend_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21'

    - name: Install dependencies
      run: |
        cd habito-frontend/
        npm install

    - name: Run frontend tests
      run: |
        cd habito-frontend/
        npm test
